### ISSUE TITLE
Windows下无法使用

### ISSUE THREAD

**Issue by cirnovsky** [AlanAlbert/musicfox#1]
mpg123似乎没用。

尝试播放时：

Unhandled exception:
Env invalid: Error: not found mpg123
#0      new Mpg123Player (package:mp3_player/src/process_player/mpg123_player.dart:12)
#1      Player.run (package:mp3_player/src/player.dart:20)
#2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:51)
#3      Player.run (package:mp3_player/src/player.dart:18)
#4      MainUI._player (package:musicfox/ui/main_ui.dart:134)
#5      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:51)
#6      MainUI._player (package:musicfox/ui/main_ui.dart:132)
#7      MainUI.play (package:musicfox/ui/main_ui.dart:590)
#8      _RootZone.runUnary (dart:async/zone.dart:1439)
#9      _FutureListener.handleValue (dart:async/future_impl.dart:141)
#10     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:682)
#11     Future._propagateToListeners (dart:async/future_impl.dart:711)
#12     Future._completeWithValue (dart:async/future_impl.dart:526)
#13     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:556)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169)

求教，感谢。

**Comment by anhoder** [comment]
没安装mpg123或者没有配置环境变量

你试下能不能在命令行直接使用mpg123

**Comment by cirnovsky** [comment]
@AlanAlbert 并没有找到mpg123Windows版本。

在sourceforge看到一个安装后添加路径没用。

**Comment by cirnovsky** [comment]
@AlanAlbert 官网翻了个墙进去了，找到了Windows版本。

谢谢作者的解答。
